# Generated by Django 4.2.7 on 2023-11-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='valor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hospedagem',
            name='valor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='apartamento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
